### Health check
GET http://localhost:3000/health HTTP/1.1  

### GET tasks
GET http://localhost:3000/api/v1/tasks HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlRONllnUHY3X01EeGlHVHAyeWs1SCJ9.eyJpc3MiOiJodHRwczovL2Rldi1yaDdteHo1Z282YzE0bXlmLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMjU0Nzg4NDYyMzI3ODA2Mzc3MCIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtcmg3bXh6NWdvNmMxNG15Zi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzYwNjI1MzEyLCJleHAiOjE3NjA2MzI1MTIsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiVFlJRUJZdEhqMmZEeEtwNGFVOTZic08xS1IyZEs1Ym8ifQ.mmUQXgqchEtdUr71oH-AsQ_YFxTsspPMplBKb_IWMIaP0GvRKSyXjW5EPwqPkedJoGHzNacyhDPcaifG2oO7hswR6iVUJmcW56Ymu3Xj36SCcl6TIbcYCLoOGjTPHyvQYOpZbKtX6O_aUqqbv6rhuVuw3x0L7oB44MjHlPLt8M_-nKCQy8k874g5Cnj_9PJJctzSQPdMLScEa12dKoWUOH12QGcsXY0EO78tFfv7KY_3o43Ewc07OKeul4ma5jdXJAf9DfkYv-zsdwVkoQ_r2oaHzdBbJlkAZN52IRO-oVjY3pWIOe9A4S6bIOeC9usSds22TQ4_56-_Q3xNcwae4A

### GET task by ID
GET http://localhost:3000/api/v1/tasks/cmgjlzz4v00023qh4gf98q3oq HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzRlNDU2Ny1lODliLTEyZDMtYTQ1Ni00MjY2MTQxNzQwMDAiLCJpYXQiOjE3NjAwMjk2MzUsImV4cCI6MTc2MDAzMzIzNSwiaXNzIjoidGFzay1tYW5hZ2VyLWFwcCJ9.ZNdfxWnPRyiM7DkVigdl5Vw5jCkvT4rX9CX49BRXWms

### GET projects
GET http://localhost:3000/api/v1/projects HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzRlNDU2Ny1lODliLTEyZDMtYTQ1Ni00MjY2MTQxNzQwMDAiLCJpYXQiOjE3NjAwMjk2MzUsImV4cCI6MTc2MDAzMzIzNSwiaXNzIjoidGFzay1tYW5hZ2VyLWFwcCJ9.ZNdfxWnPRyiM7DkVigdl5Vw5jCkvT4rX9CX49BRXWms


### GET project by ID
GET http://localhost:3000/api/v1/projects/cmgjlzz3100003qh4fme29owm HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzRlNDU2Ny1lODliLTEyZDMtYTQ1Ni00MjY2MTQxNzQwMDAiLCJpYXQiOjE3NjAwMjk2MzUsImV4cCI6MTc2MDAzMzIzNSwiaXNzIjoidGFzay1tYW5hZ2VyLWFwcCJ9.ZNdfxWnPRyiM7DkVigdl5Vw5jCkvT4rX9CX49BRXWms

### GET project's tasks
GET http://localhost:3000/api/v1/projects/cmgjlzz3100003qh4fme29owm/tasks HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzRlNDU2Ny1lODliLTEyZDMtYTQ1Ni00MjY2MTQxNzQwMDAiLCJpYXQiOjE3NjAwMjk2MzUsImV4cCI6MTc2MDAzMzIzNSwiaXNzIjoidGFzay1tYW5hZ2VyLWFwcCJ9.ZNdfxWnPRyiM7DkVigdl5Vw5jCkvT4rX9CX49BRXWms


